#!/bin/bash
# Copyright (c) 2013 Tim Cooper
# See LICENSE
#

YOLO_BIN="yolo"

while true
do
    current=$($YOLO_BIN current)
    # No current task
    if [ "$?" != "0" ]
    then
        task=$(zenity \
            --entry \
            --title="yolo" \
            --text="Enter a task to complete" 2> /dev/null)
        if [ "$?" != "0" ]
        then
            exit
        fi
        $YOLO_BIN set "$task" < /dev/null
        if [ "$?" = "0" ]
        then
            exit
        fi
    else
        selection=$(echo -e "\nDone\n\nAbandon" |
            zenity \
                --list \
                --title="yolo" \
                --radiolist \
                --column="" \
                --column="Action" \
                --print-column=2 \
                --text="$current" 2> /dev/null)
        if [ "$?" != "0" ]
        then
            exit
        fi
        case "$selection" in
            "Done")
                $YOLO_BIN done
            ;;
            "Abandon")
                $YOLO_BIN abandon
            ;;
        esac
    fi
done
